=begin
#Intrinio API

#Welcome to the Intrinio API! Through our Financial Data Marketplace, we offer a wide selection of financial data feed APIs sourced by our own proprietary processes as well as from many data vendors. For a complete API request / response reference please view the [Intrinio API documentation](https://intrinio.com/documentation/api_v2). If you need additional help in using the API, please visit the [Intrinio website](https://intrinio.com) and click on the chat icon in the lower right corner.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Intrinio::FilingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FilingApi' do
  before do
    # run before each test
    @instance = Intrinio::FilingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FilingApi' do
    it 'should create an instance of FilingApi' do
      expect(@instance).to be_instance_of(Intrinio::FilingApi)
    end
  end

  # unit tests for filter_filings
  # Filter Filings
  # Returns filings that match the specified filters
  # @param company Filings for the given &#x60;company&#x60; identifier (ticker, CIK, LEI, Intrinio ID)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :report_type Filter by report type
  # @option opts [Date] :start_date Filed on or after the given date
  # @option opts [Date] :end_date Filed before or after the given date
  # @option opts [String] :next_page Gets the next page of data from a previous API call
  # @return [ApiResponseFilings]
  describe 'filter_filings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_filings
  # Get All Filings
  # Returns all filings
  # @param [Hash] opts the optional parameters
  # @option opts [String] :next_page Gets the next page of data from a previous API call
  # @return [ApiResponseFilings]
  describe 'get_all_filings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_filing_by_id
  # Get a Filing by ID
  # Return the filing with the given ID
  # @param id The Intrinio ID of the Filing
  # @param [Hash] opts the optional parameters
  # @return [Filing]
  describe 'get_filing_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
